### ISSUE TITLE
leddarVu8

### ISSUE THREAD

**Issue by panecho** [lasdasdas/leddarone#1]
Can or Will this package support leddarVu8?

**Comment by lasdasdas** [comment]
Hi @ZhengPan2014 , this package does unfortunately not support the Vu8.
I would love to add support for the Vu8 but I don't have one avaliable to test the drivers. If you want to contribute I can help you to do it.

**Comment by panecho** [comment]
@lasdasdas  I got a SDK support from the supplier, thank you!
